name: Release

on:
  push:
    tags:
      - 'v*'


jobs:

  goreleaser:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - uses: actions/setup-go@v7
        with:
          go-version: stable

      - uses: goreleaser/goreleaser-action@v7
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:

      - uses: actions/checkout@v7

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Deploy to Deno Deploy
        env:
          DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
        run: deno deploy --non-interactive --prod --org ${{ secrets.DENO_DEPLOY_ORG }} --app acp edge

